### ISSUE TITLE
Mob spawn rate unchanged

### ISSUE THREAD

**Issue by bbgott** [lumien231/Bloodmoon#10]
The mob spawn rate does not seem to be affected by the blood moon.  When I use the "/bloodmoon force" command and then accelerate time to just before 12000, I get the "The Blood Moon is rising..." message and the red moon rises, but the mob spawning rate seems to be completely vanilla.

MC: 1.10.2
Forge: 12.18.2.2107
Bloodmoon: 1.9.4-1.4.1

**Comment by lumien231** [comment]
Can you reproduce this with no other mods installed?

**Comment by bbgott** [comment]
Oh yeah, I should've tested that first. I'll test it with just bloodmoon and report back. I do currently have a handful of other mods installed.

**Comment by bbgott** [comment]
Ok, had a chance to run a test with just the bloodmoon mod installed. It still doesn't seem like the mob spawn rate doesn't change.  I used the versions I listed above.

**Comment by lumien231** [comment]
Weird, i just tried it and it seems to work fine, how exactly did you test it? 
I created a flat world ran /bloodmoon force, set time to 11900 waited for the message and then set time to 16000 and mobs started spawning instantly.

**Comment by bbgott** [comment]
Hmmm. I didn't use a flat world, I used a default world. Otherwise I did
the exact same thing. I will try it with a flat world and see if I can
reproduce your results.

**Comment by bbgott** [comment]
Ok, yes I was able to reproduce your results on a flat world.  If I follow your steps I see a massive number of mobs spawn, as I would expect in a blood moon.  When I perform the exact same steps on a default world, I don't see the same mob spawning.

**Comment by FELITH** [comment]
I confirm to bbgott.
