### ISSUE TITLE
Warning: coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion

### ISSUE THREAD

**Issue by kirchner-trevor** [lumien231/Bloodmoon#13]
**Issue**
When starting my server Forge Mod Loader displays the following message.

[main/WARN] [FML]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

The mod appears to work fine and does not crash, however I do not know what affect this may have.

**Steps to Reproduce**
1. Add Bloodmoon jar to mods folder
2. Start server

**Logs**
[fml-server-latest.txt](https://github.com/lumien231/Bloodmoon/files/677387/fml-server-latest.txt)

**Versions**
Bloodmoon: 1.11-1.5.1
Forge: 1.11-13.19.1.2199-universal
Minecraft: 1.11

**Comment by lumien231** [comment]
Doesn't have any effect.
