### ISSUE TITLE
Incompatibility with Astral Sorcery

### ISSUE THREAD

**Issue by Sunconure11** [lumien231/Bloodmoon#18]
https://github.com/HellFirePvP/AstralSorcery/issues/116

"that's why AS is incompatible with bloodmoon - lumien ASM's the renderSky method to add his moon colorization hook - which is a terrible implementation. to recolor sun/moon you don't need ASM at all.
tl;dr his implementation is terrible and doesn't care if other mods change the sky. if he had implemented it properly, compatibility would be no issue"

**Comment by lumien231** [comment]
Wow what a nice message :). I'll see what i can do, i can probably change the moon texture directly instead of modifying its color when it's drawn.

**Comment by HellishINC** [comment]
I'm guessing that if you replace the texture, resource packs will also have to provide a blood moon'd texture as well?

**Comment by lumien231** [comment]
No, i'll just modify the texture on the fly. It will use the moon texture of the active resource pack.

**Comment by FireController1847** [comment]
I can confirm this issue, and hope it gets fixed soon.

**Comment by FireController1847** [comment]
Eventually™

**Comment by darchitectlp** [comment]
Any word on this? Love me some red light on a bloodmoon... I'm also getting a weird yellow tint when I use night vision, and I'm having a hard time tracking down what's causing it.

**Comment by ate0ate** [comment]
Geeze, this sure would be a great little bit of mod integration to have but I gotta agree with Lumien about the original message. Not exactly the most pleasant way to go about pointing out the issue lol.

**Comment by FireController1847** [comment]
Huzzah!
