### ISSUE TITLE
Crash with Bloodmoon and wolfarmor

### ISSUE THREAD

**Issue by vico93** [lumien231/Bloodmoon#28]
When enabling Wolfs howling on full moon + bloodmoons happening every full moon at the first bloodmoon in the world i got a crash (first gist). The second gist is when i reattempt to open the world.

https://gist.github.com/vpontin/bc493c6d86d3984a1a1e3e691f25a3fd

Since i dont know what mod is responsible i will drop the same issue here an there.

https://github.com/CenturionFox/wolfarmor/issues/39

**Comment by lumien231** [comment]
My Fault. Calling World.getMoonPhase() from a server thread seems dangerous though since it's client side only. Might crash on a dedicated server without rt as well.

**Comment by vico93** [comment]
@lumien231 Also @CenturionFox [fixed that in his side too](https://github.com/CenturionFox/wolfarmor/issues/39#issuecomment-390279510).
Will test soon, but i think this is fixed for now.
