### ISSUE TITLE
[Suggestion] Command to force Bloodmoon

### ISSUE THREAD

**Issue by Xarmat-GitHub** [lumien231/Bloodmoon#52]
### Description
For Modpack Makers it is important to have control over the player experience.
So a command to trigger Bloodmoon would be a great thing.

**Functionality**
Command: /bloodmoon 
+ now -> Set time to night and starts instantly a bloodmoon event
+ 0 -> Next Night will start a bloodmoon event
+ 1-99 -> In "X" days there will be a bloodmoon event
+ end -> End the bloodmoon and when a event is set in the future, it will be disabled 

**Example**
/bloodmonn 5 -> In 5 days there will be a bloodmoon event

**Config**
- Allow Command in Survival = false
- Print a Massage to all Players when a bloodmoon event were set by command= true ("A Bloodmoon will rice in 2 days, prepare...")

**Note:**
- When a command is executed, disable bloodmoon until this night. After that, use config values

**Comment by lumien231** [comment]
There is **/bloodmoon force** and **/bloodmoon stop** which do force a bloodmoon for the next night / stop the current one.

**Comment by Xarmat-GitHub** [comment]
Thanks for the feedback, I missed that.
This Ticket can be closed. All other features can be made with modding tools and command blocks.

**CLOSE**
