### ISSUE TITLE
bloodmoon-1.9-1.4 crashes dedicated forge server 1.9 build 1809 on startup

### ISSUE THREAD

**Issue by kreezxil** [lumien231/Bloodmoon#6]
Issue: {bloodmoon-1.9-1.4 crashes dedicated forge server 1.9 build 1809 on startup}

https://gist.github.com/edb1461328c4af987234

**Comment by lumien231** [comment]
Yeah, the latest forge version requires most mods to recompile / change a few small things. Will fix it tomorrow.
